### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by sjnam** [ascherer/cweb#15]
In a section of the file `ctangle.w`, when the TeX part is empty and the C part is an unnamed section starting with `@c` or `@p`, how about start with
```
@
@c
```
rather than `@ @c` at the beginning of the section? When you start the section with `@ @c`, the first line of the C part comes out in the same line as the section number, which is a bit strange to see. This applies to `common.w` and `cweave.w` files as well.
Thank you.

**Comment by ascherer** [comment]
It's been that way all along.  Changing this convention would most certainly result in a different pafe count and a host of necessary adaptions.  So I'll leave it that way.
