### ISSUE TITLE
Add support for variadic macros.

### ISSUE THREAD

**Issue by ascherer** [ascherer/cweb#17]
C99/C++11 introduced "variadic macros", but `CWEAVE` objects to
```
@d wterm(FMT,...) fprintf(out,FMT,##__VA_ARGS__)
```
`CTANGLE` has no problem with this line.

Replacing this with
```
@d wterm@t\4\,@>@[FMT,...]@>@t\quad@>fprintf(out,FMT,##__VAR_ARGS__)
```
makes `CWEAVE` happy, but the C compiler bails on `wterm (` output by `CTANGLE`.

Note that the explicit
```
#define wterm(FMT,...)@t\quad@>fprintf(out,FMT,##__VA_ARGS__)
```
works with both `CWEAVE` and `CTANGLE` and their output, apart from the necessary `@t\quad@>` helper.

**Comment by texdraft** [comment]
I'm not sure what the proper protocol for submitting patches is, but the following change to `cweave.w` seems to work:

```
@x line 4148
  reswitch: switch (next_control=get_next()) {
      case '(': case ',': app(next_control); goto reswitch;
      case identifier: app_cur_id(false); goto reswitch;
      case ')': app(next_control); next_control=get_next(); break;
      default: err_print("! Improper macro definition"); break;
      }
@y
  reswitch: switch (next_control=get_next()) {
      case '(': case ',': app(next_control); goto reswitch;
      case identifier: app_cur_id(false); goto reswitch;
      case @q(@>')': app(next_control); next_control=get_next(); break;
      case dot_dot_dot: app_str("\\,\\ldots\\,");
@.\\,@>
@.\\ldots@>
        app_scrap(raw_int,no_math);
        next_control=get_next();
        if (next_control==')') {
          app(next_control);
          next_control=get_next();
          break;
        } /* otherwise fall through */
      default: err_print("! Improper macro definition"); break;
      }
@z
```

It catches `...` in the parameter list and treats it as it treats `...` elsewhere. An error is reported if anything besides `)` follows `...`.

I'm not a huge fan of the code duplication with both the `)` branch and section 190, but avoiding it would require restructuring the code.

**Comment by ascherer** [comment]
If you want to submit patches then you should
* clone this project on Github
* check out your copy to your local machine
* (optionally) create a working branch in your copy
* submit your work to Github
* compare your branch with my master
* create a pull request

I'll try your suggestion directly.

**Comment by texdraft** [comment]
OK, thanks. I've added support for attributes and C++ number syntax (and some other C++ constructs) to `CWEAVE`, but it's currently in a change file. Would it be better to be working instead with the `.w` file directly when implementing stuff like this?

**Comment by ascherer** [comment]
For `@d` it works fine, but the formatting of a manual `#define` is slightly off:
```
@* Variadic macros.

@d eprintf1(...) fprintf(stderr, ## __VA_ARGS__ )

@c
#include <stdio.h>
#include <stdlib.h>
@#
#define eprintf2(fmt,...) fprintf(stderr, fmt __VA_OPT__(,) __VA_ARGS__ )
@#
int main(void)
{
   eprintf1("%s:%d\n", __FILE__, __LINE__);
   eprintf2("%s:%d\n", __FILE__, __LINE__);
   return EXIT_SUCCESS;
}

@* Index.
```

**Comment by ascherer** [comment]
It's much better to work directly with the `.w` sources and let `git`/Github do the bureaucratic work.  (I can, of course, incorporate change files with `tie`/`ctie`.)

**Comment by texdraft** [comment]
Sounds good.

The formatting issue appears to be related to `CWEAVE`'s handling of non-`@d` definitions in general, and I confess that I don't fully understand that area of the program. Perhaps: Make `CWEAVE` treat `@d` and `#define` identically (I realize that this is not trivial), except that `#define` sets a flag saying not to ignore line endings.

**Comment by texdraft** [comment]
Oh, sorry, one more protocol question. My changes add productions to `CWEAVE`'s grammar. Is it better to just tack them on at the end of `prod.w` or to incorporate them more carefully into the table, altering most of the production numbers in the process?

**Comment by ascherer** [comment]
Please add at the end.
