### ISSUE TITLE
Wrong formatting with C99 compound literal

### ISSUE THREAD

**Issue by Zeta611** [ascherer/cweb#22]
I've been using original CWEB to try literate programming for the first time.
Everything was fine, until I noticed a strange formatting when using [C99 compound literal syntax](https://en.cppreference.com/w/c/language/compound_literal).
Then I tried CWEB 4.2, and the problem was not resolved.

Here is a MWE that demonstrates the problem:
```c
@* Hello CWEB.
@c
#include <stdio.h>

struct T {
	int a;
};

struct T tok(void) {
	return (struct T){.a = 1}; // C99 compound literal
}

int main(void)
{
	struct T = tok();
	return 0;
}
```

[This](https://github.com/ascherer/cweb/files/6290053/test.pdf) is the output PDF build with `cweave` and  `pdftex`.

In the meantime, I can try manually breaking the lines with `@;`, but I can't see how to manually indent/unindent wrongly formatted code.

**Comment by ascherer** [comment]
This particular example can be fixed with
```
return @[(struct T){.a = 1}@]; // C99 compound literal
```
which works with CWEB 3.6 (May 2005) and up.

**Comment by ascherer** [comment]
Here's a larger example with a few more tweaks:
```
@* C/99 Compound Literals.

@c
@<\#|include|s@>@;
@<Structure@>@;
@<Declaration@>@;
@<Definition@>@;
@<Output@>@;
@<Main@>@;

@ @<\#|inc...@>=
#include <stdio.h> /* |printf| */
#include <string.h> /* |memcpy| */

@ @<Struct...@>=
struct T
{
	int a;
	char* b;
} t2;

@ @<Decl...@>=
void g(const struct T* t);

@ @d bufsiz 10

@<Def...@>=
void f(void)
{
@t\2\2@>
	int *x = @[(int [bufsiz])@t @>{42}@];

	t2 = @[(struct T) {43, "world"}@];
	g( @[&(struct T)@t @>{@, .b="hello", .a=47 @,}@] );
	g( @[&(struct T) {43, "bye"}@] );
@t\2\2@>
	memcpy(x, @[(int[])@t @>{1, 2, 3}@], 3*sizeof(int));
	for (int i=0; i<bufsiz; ++i)
		printf("x[%d]==%d\n", i, x[i]);
}

@ @<Out...@>=
void g(const struct T* t)
{
	printf("struct T { a=%d, b=%s }\n", t->a, t->b);
}

@ @<Main@>=
int main(void)
{
	f();
}
```
