### ISSUE TITLE
Option for regular comments. 

### ISSUE THREAD

**Issue by MirkoHernandez** [ascherer/cweb#23]
Is there a cweave  option ( or workaround) to process comments as regular comments (not as TEX)?

cweb  3.64e (the win32 version) includes some options that I find really useful that do not seem to be present in  cweb 4.3.

-  ‘t’ respects both regular and trailing comments.
- ‘g’ respects blank lines.
- ‘z’ indicates plain text comments.

The source for the win32 version  does not seem to be  available in literateprogramming.com so I was wondering -  is there is a way to achieve something similar in cweb 4.3?

**Comment by ascherer** [comment]
From the PDF on `literateprogramming.com`, I see that "Frank A. Krueger" (@praeclarum?) had added an extended set of options to both `ctangle` and `cweave` that look quite interesting.

However, as I don't use MS Windows, I can't install `cweb.exe` to test the software (from 2005!). There are no plans at this time to "reinvent" similar functionality for `CWEB 4` from scratch.

**Comment by ascherer** [comment]
A quick glance at `miktex.org`, I detect that "nowadays" MikTeX uses `CWEB 3.64ag` (native Knuth version from 2016?). Again, I have to resources to test this.

**Comment by ascherer** [comment]
Please revert to **CWEB 4.2**. **CWEB 4.3** is seriously broken and should **not** be used for production.

**Comment by MirkoHernandez** [comment]
Thank you, I will use that version from now on, also  it turns out that  the win32 installer includes the source code so I will try to use that particular version of cweave until I find a work around for the other options.
