### ISSUE TITLE
About license for the project

### ISSUE THREAD

**Issue by chenrui333** [ascherer/cweb#29]
👋  while I was trying to [update the livecheck ](https://github.com/Homebrew/homebrew-core/pull/89397)for the formula in homebrew side, I found that is no license for the repo? I wonder if we can add a SPDX license for the project. Thanks!

**Comment by ascherer** [comment]
Will check ASAP.

**Comment by ascherer** [comment]
The legal situation is quite consistent:

From the `README` file and the **main** `.w` files, e.g., `ctangle.w`:
```
% This file is part of CWEB.
% This program by Silvio Levy and Donald E. Knuth
% is based on a program by Knuth.
% It is distributed WITHOUT ANY WARRANTY, express or implied.
% Version 4.5 --- July 2021

% Copyright (C) 1987,1990,1993,2000 Silvio Levy and Donald E. Knuth

% Permission is granted to make and distribute verbatim copies of this
% document provided that the copyright notice and this permission notice
% are preserved on all copies.

% Permission is granted to copy and distribute modified versions of this
% document under the conditions for verbatim copying, provided that the
% entire resulting derived work is given a different name and distributed
% under the terms of a permission notice identical to this one.
```

From [the CTAN package page](https://ctan.org/pkg/cweb) we come to [the Knuth License](https://ctan.org/license/knuth):
```
This software is copyright[ed] and you are explicitly granted a license
which gives you, the “user” of the software, legal permission
to copy, distribute and/or modify the software, so long as
if you modify the software then it carry a different name
from the original software. 
```
I do not know which of [the SPDX Licenses](https://spdx.org/licenses/) matches Knuth's legalese.

@kberry I'll send you this comment as email later for ideas and suggestions how to procede.

**Comment by ascherer** [comment]
Here are a few external users of this `CWEB` project:

- [Homebrew](https://formulae.brew.sh/formula/cweb)
- [Plan9](https://git.sr.ht/~ft/cweb)

**Comment by ascherer** [comment]
From the Homebrew stats I see that package `texlive` is in much more common use than package `cweb`. It is worth noting that the `CWEB` binaries from `texlive` are much enhanced in comparison to the “original” programs. In addition to `ctangle` and `cweave`, the `ctwill` variant (plus utilities and macros) is included.

With regards to the “license”, `CWEB` is copyrighted as stated in the sources. The `CWEBbin` extensions, which modify the `CWEB` sources with “change fies”, are released under the “MIT License”, including the modifications for “TeX Live”.
