### ISSUE TITLE
cweave creates unwanted file when cweb file does not exist

### ISSUE THREAD

**Issue by igor-liferenko** [ascherer/cweb#3]
If either web file or change file is not found, or both, then .tex file is created, containing just "\input cwebma".
Afterwards it is necessary to remove this file manually.
The warning would be enough.

**Comment by ascherer** [comment]
This is a feature. The output file(s) are opened in ```common_init()```, the input file(s) are opened in ```reset_input()```, which is used in ```phase_one()``` (used both in **ctangle** and **cweave**) and ```phase_two()```(used only in **cweave**).

**Comment by ascherer** [comment]
"Feature" in this case means "non-catastrophic infelicity" that will never be fixed. See the "Errata section" on page http://cs.stanford.edu/~uno/cweb.html .

**Comment by ascherer** [comment]
From a programmer's point of view, the asymmetric/nonexistent calls to ```fopen()``` and ```fclose()``` in the various ```.w``` files could be considered more problematic.
