### ISSUE TITLE
license for the project

### ISSUE THREAD

**Issue by chenrui333** [ascherer/cweb#31]
👋 just curious, what is the license for this project. I was kind of assuming it would be `Latex2e`, but I saw there is one clause difference between the two.

> Permission is granted to copy and distribute translations of this manual into another language, under the above conditions for modified versions.

Can you clarify it or maybe include `LICENSE` or `COPYING` as part of the source tarball distribution? Thanks a lot!

**Comment by ascherer** [comment]
The whole CWEB package is distrubted under the [Knuth License](https://ctan.org/license/knuth). The original wording can be found in all of the major source files and at the beginnig of the `README` file. There's no need for an extra `LICENSE` file just for Github.

**Comment by ascherer** [comment]
You had asked the same question before: #29

**Comment by chenrui333** [comment]
sorry about re-raising the same issue all over again.

I read thru the comments on the previous issue and they are pretty helpful for me to move forward. Thanks!
