### ISSUE TITLE
Incorrect type definition

### ISSUE THREAD

**Issue by ascherer** [ascherer/cweb#34]
[`gb_words.w`](https://github.com/ascherer/sgb/blob/master/gb_words.w#L405) gets clobbered after section 23, because `hash_prime` gets treated as a **type** instead of as a _value_; see attached [gb_words.pdf](https://github.com/ascherer/cweb/files/8614237/gb_words.pdf).

A temporary solution is
```
typedef Vertex @[*hash_table[hash_prime]@];
```
but, of course, we can't impose that on The Stanford GraphBase et al.

**Comment by texdraft** [comment]
This one is my fault. Production 117 should check for `lbrack` as well as `lpar` and `exp` and `cast`.

**Comment by ascherer** [comment]
@texdraft Thanks!
