### ISSUE TITLE
Formatting glitches in primitive C code

### ISSUE THREAD

**Issue by ascherer** [ascherer/cweb#36]
Section §1 of [queen.w](https://github.com/ascherer/sgb/blob/master/queen.w) gets clobbered.

Temporary fix:
```
diff --git a/queen.w b/queen.w
index 6d9d09b..f22164b 100644
--- a/queen.w
+++ b/queen.w
@@ -18,12 +18,12 @@ You might find it interesting to compare the output of {\sc QUEEN} with
 the contents of \.{queen.gb}; the former is intended to be readable
 by human beings, the latter by computers.
 
-@p
+@p@t$\!\!\!$@>@+
 #include "gb_graph.h" /* we use the {\sc GB\_\,GRAPH} data structures */
 #include "gb_basic.h" /* we test the basic graph operations */
 #include "gb_save.h" /* and we save our results in ASCII format */
 @#
-main()
+@;main()
 {@+Graph *g,*gg,*ggg;
   g=board(3L,4L,0L,0L,-1L,0L,0L); /* a graph with rook moves */
   gg=board(3L,4L,0L,0L,-2L,0L,0L); /* a graph with bishop moves */
```
[queen_bad.pdf](https://github.com/ascherer/cweb/files/8618675/queen_bad.pdf)

**Comment by ascherer** [comment]
Here is a minimal working example.
[hello.tar.gz](https://github.com/ascherer/cweb/files/8619368/hello.tar.gz)

**Comment by ascherer** [comment]
Here's a hack for both issues:
```
@* Programm.

@c
@t\4\enspace@>
@+
#include <stdio.h>
#include <stdlib.h>
@#
@;
int main(void)
{
  printf("Hello, world!\n");
  return EXIT_SUCCESS;
}

@* Index.
```

**Comment by ascherer** [comment]
The general problem seems to boil down to
```
#any_preprocessor_line
function definition
```

**Comment by texdraft** [comment]
Changing the code for production 38 to

```
  big_app1(pp); big_app(dindent); reduce(pp,1,fn_decl,0,38);
```

seems to fix it.

**Comment by ascherer** [comment]
Right! That's exactly what `prod.w` says (see section **111** of `cweave.pdf`). I'll apply your correction later today.
Thanks for your help, as always!

**Comment by ascherer** [comment]
Note to self: In `queen.w` it is necessary to amend *main()* with return type **int** to mae things work correctly. Users of SGB are well advised to apply `PROTOTYPES/queen.ch` when working with this example.

**Comment by ascherer** [comment]
Note to self: Inspect production rule 73.

**Comment by ascherer** [comment]
Note to self: Swapping in rule 1 fixes `queen.w` completely. So, I'll have to thoroughly check rules 1, 38, 73 after the proposed change.

**Comment by texdraft** [comment]
The first approach, while being perhaps more logical, would probably be more difficult to implement.

Removing production 83 appears to solve this issue entirely, while not changing the output of CWEAVE on programs that it formatted correctly. In `queen.w` an irreducible scrap is left but the resulting TeX file isn't affected. You could add a rule that changes `insert function` into `function` if you want to get rid of it.

**Comment by ascherer** [comment]
This looks extremely promissing! And extremely easy to implement at that.

Tomorrow I'll check the results on the “usual suspects” before going live.

**Comment by ascherer** [comment]
This time not even **CTWILL** had any objections.
