### ISSUE TITLE
`cwebmac` missing with `texlive` ubuntu package despite finding `cweave`

### ISSUE THREAD

**Issue by tvercaut** [ascherer/cweb#42]
Sorry if this is not the right place to ask this question. I have been trying to automate the creation of a cweb document with github actions:
https://github.com/tvercaut/iad

This currently works but takes about an hour to run due to teh installation of `texlive-full`. I tried installing only `texlive` as I thought this would be sufficient to get cweb:
https://manpages.ubuntu.com/manpages/jammy/man1/cweb.1.html

However, it then stumbles by not finding `cmacweb` despite having found `cweave`:
```
cweave -bph ad || (echo "cweave exited with code $? - continue anyway"; exit 0)

! Never used: <Definition for |swrarray|>
! Never used: <debug print angles>
! Never used: <unused fragment one>
! Never used: <unused fragment two>(Did you see the warning message above?)
cweave exited with code 5 - continue anyway
pdftex ad
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian) (preloaded format=pdftex)
 restricted \write18 enabled.
entering extended mode
(./ad.tex
! I can't find file `cwebmac'.
l.1 \input cwebmac
make[1]: *** [Makefile:71: ad_doc] Error 1
```

Is there a package that can be installed on ubuntu or a step that I would be missing with `texlive` only to get a fully working cweb setup?

**Comment by tvercaut** [comment]
I have now found that installing `texlive-extra-utils` on top of `texlive` solves my issue. Not sure if this is expected but if so, feel free to close this issue.

**Comment by ascherer** [comment]
I'm glad you were able to resolve this issue. I'm not familiar with Ubuntu's TeX Live packaging, so I couldn't provide much help.

Alternatively, I'd suggest to follow the [general installation recipe](https://www.tug.org/texlive/doc/texlive-en/texlive-en.html#x1-140003) with `scheme-minimal` and then add the `cweb` package with `tlmgr install cweb` (it will pick the system-dependent binaries automatically).

See also https://tex.stackexchange.com/questions/397174/minimal-texlive-installation
