### ISSUE TITLE
cwebacromac.tex: possible unintended space after }

### ISSUE THREAD

**Issue by kberry** [ascherer/cweb#56]
Hi Andreas - In cwebacromac.tex, as it currently is in TL, line 75 is:
```
\else \addtokens\toksB{\the\toksD} \ifx\first,\addtokens\toksB{\space}\fi
```
That space after `\toksD}` looks spurious. I doubt it makes any difference in practice, but since the code seems to be careful about avoiding all such spaces inside macros otherwise, reporting. If the point is to stop expansion of course `\relax` is the no-op way to do that.

Or maybe all this code is gone now per Martin's profiling? Sorry for not checking.

**Comment by ascherer** [comment]
This line has been that way _ab origine_ in [Cruzius' cwebmac-pdf.tex (line 145)](https://github.com/ascherer/cweb/commit/b5a4f8586675e90dc064004fb7ab35ead748aba4#diff-6098d40edbac81ce5353328120cbcd16b9025ec3ac23d0dc5b3879674dca1655R145) of December 1999. Of course, one wants spaces in the comma-separated list of section numbers. I assume it's the same `\space` as in [Martin's code at line 36](https://github.com/ascherer/cweb/blob/master/cwebacromac.tex#L36).

**Comment by ascherer** [comment]
The previous comment referred—incorrectly—to the `\space` after `\tokB`.

The space after `\toksD}` stems from the _line break_ between [lines 144–145 in César Crusius``cwebmac.pdf.tex`](https://github.com/ascherer/cweb/commit/b5a4f8586675e90dc064004fb7ab35ead748aba4#diff-6098d40edbac81ce5353328120cbcd16b9025ec3ac23d0dc5b3879674dca1655R144-R145)  of CWEB 3.5 (December 1999).

**Comment by ascherer** [comment]
The spurious whitespace (line break) is virtually everwhere:

- [`pdfwebmac.tex`](https://github.com/ascherer/web/blob/master/pdfwebmac.tex#L90) (obsolete)
- [`xewebmac.tex`](https://github.com/ascherer/web/blob/master/xewebmac.tex#L35) (obsolete)
- [`pwebmac.tex`](https://github.com/ascherer/web/blob/master/pwebmac.tex#L124) (fixed today)
